### ISSUE TITLE
ssr-client闪退

### ISSUE THREAD

**Issue by jerryqbh** [ShadowsocksR-Live/ssr2heroku#1]
完全按照您的教程做完以后，windows系统下打开ssr-client就闪退，麻烦问问该如何解决

**Comment by ssrlive** [comment]
在 cmd 命令行下执行，ssr-client 命令，看看输出是什么。复制、粘贴这里看看。

**Comment by jerryqbh** [comment]
该怎么执行命令啊。。。是不是./ssr-client -c /your/path/of/config.json这个命令？

**Comment by ssrlive** [comment]
……

**Comment by ssrlive** [comment]
算了吧。
